<Project>
    <!-- Nhúng file version riêng biệt để dễ dàng cho bot CI/CD đọc và sửa -->
    <Import Project="Version.props" Condition="Exists('$(MSBuildThisFileDirectory)Version.props')" />

    <PropertyGroup>
        <!-- Compiler Settings -->
        <TargetFramework Condition="'$(TargetFrameworks)' == ''">net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisLevel>latest</AnalysisLevel>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    
        <!-- Ép buộc toàn bộ code phải tương thích với AOT và Trimming -->
        <IsAotCompatible>true</IsAotCompatible>
        <IsTrimmable>true</IsTrimmable>

        <!-- Gom toàn bộ thư mục bin/ và obj/ của mọi project về chung một thư mục artifacts/ ở root (Sạch sẽ repo) -->
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <NoWarn>$(NoWarn);CS1591;CA1710;CA2000;CA1305;CA1307;CA2016;SYSLIB1045;IDE0270;IDE0300;IDE0305;IDE0005;IDE0008;IDE0009;IDE0011;IDE1006;CA1031;CA5351;CA5350;CA2007;IL2026;IL3050;CA1062;CA1861;CA1822;CA1054;CA1056;CA1707;CA1711;CA1716;CA1720;CA2234;IDE0007;IDE0028;IDE0047;IDE0048;IDE0053;IDE0058;IDE0060;IDE0090;IDE0130;IDE0290</NoWarn>
    </PropertyGroup>

    <!-- Debug: Ép FULL thông tin và Source Code vào DLL để dễ fix lỗi lúc dev -->
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugType>embedded</DebugType>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>false</IncludeSymbols>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>portable</DebugType>
        <EmbedUntrackedSources>false</EmbedUntrackedSources>
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <!-- Thông tin tác giả mặc định -->
    <PropertyGroup>
        <Authors>PPN Corporation</Authors>
        <Company>PPN Corporation</Company>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Copyright>Copyright (c) 2026 PPN Corporation. All rights reserved.</Copyright>
    </PropertyGroup>
</Project>
