name: "CI: Linux Build & Test"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: ["master", "main"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"
      - "*.slnx"
  pull_request:
    branches: ["master", "main"]
    paths:
      - "src/**"
      - "tests/**"
      - "*.sln"
      - "*.slnx"

permissions:
  contents: read
  checks: write
  pull-requests: write # required for test result comments

jobs:
  build:
    name: Linux
    uses: ./.github/workflows/_build.yml
    with:
      os: ubuntu-latest
      project: src/Zalo.Net.slnx
      test: tests/Zalo.Net.Tests.slnx
      deploy: false
      coverage: true
